// pages
import Head from 'next/head';
import About from '../components/About';
import Contact from '../components/Contact';
import Main from '../components/Main';
import Projects from '../components/Projects';
import Skills from '../components/Skills';
//i18n
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import WppButton from '../components/WppButton';
export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['home'])),
    },
  };
}

export default function Home(props) {
  return (
    <div>
      <Head>
        <title>João | Fron-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="description" content="Freelancer web development. Web developer website, landing page, ecommerce and mobile apps. Digital Marketing Service."/>
        <meta property="og:description" content="Freelancer web development. We develop website, landing page, ecommerce and mobile apps. Digital Marketing Service."/>
        <meta property="og:image" content="https://www.jmazer.net/assets/logosm.png"/>
        <meta property="og:image:width" content="200"/>
        <meta property="og:image:height" content="200"/>
        <meta property="og:title" content="JMAzer"/>
        <meta property="og:type" content="website"/>
        <meta name="googlebot" content="index,follow"/>
        <meta property="og:url" content="https://jmazer.net"/>
        <meta
          name="keywords"
          content="web, web developer, web desing, freelance, freelancer, projetos, internet, impulsionar, website, leverage business, responsive, frontend, front-end, development, wordpress, next, react, next.js, react.js, bootstrap, material ui, tailwind, Rio de janeiro, RJ"
        />
        <meta name="apple-mobile-web-app-title" content="JMAzer - FrontEnd Developer" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="orange" />
        <meta name="author" content="JMAzer" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WppButton />
      <Main />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </div>
  );
}
